# Generated by Django 6.1.1 on 2026-09-14 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolrent', '0002_categoria_ferramenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='toolrent.ferramenta')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='toolrent.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluguel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='toolrent.aluguel')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='toolrent.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='toolrent.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='toolrent.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(max_length=500)),
                ('aluguel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacoes', to='toolrent.aluguel')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='toolrent.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='toolrent.usuario')),
            ],
        ),
    ]
