# Generated by Django 6.1.1 on 2026-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolrent', '0006_detalhes_ferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='exige_caucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='periodo_minimo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='politica_cancelamento',
            field=models.CharField(default='Flexível', max_length=20),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='preco_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='status_aprovacao',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
