# Generated by Django 6.1.1 on 2026-09-22 23:01

from django.db import migrations, models


def publicar_anuncios_existentes(apps, schema_editor):
    ferramenta = apps.get_model('toolrent', 'Ferramenta')
    ferramenta.objects.filter(status_aprovacao='PENDENTE').update(status_aprovacao='PUBLICADO')


class Migration(migrations.Migration):

    dependencies = [
        ('toolrent', '0007_ferramenta_entrega_ferramenta_exige_caucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='status_aprovacao',
            field=models.CharField(default='PUBLICADO', max_length=20),
        ),
        migrations.RunPython(publicar_anuncios_existentes, migrations.RunPython.noop),
    ]
