# Generated by Django 6.1.1 on 2026-09-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolrent', '0008_alter_ferramenta_status_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
