# Generated by Django 6.1.1 on 2026-09-22 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolrent', '0009_foto_arquivo_alter_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='toolrent.ferramenta'),
        ),
    ]
